[package]
name = "cranko"
version = "0.0.0-dev.0"
authors = ["Peter Williams <peter@newton.cx>"]
edition = "2018"

[dependencies]
anyhow = "^1"
cargo_metadata = "^0.10"
chrono = "^0.4"
ci_info = "^0.10"
dynfmt = { version ="^0.1", default-features = false, features = ["curly"] }
git2 = "^0.13"
lru = "^0.6"
petgraph = "^0.5"
semver = "^0.9"
serde = { version = "^1.0", features = ["derive"] }
structopt = "^0.3"
textwrap = "^0.12"
thiserror = "1.0"
toml = "^0.5"
toml_edit = "^0.2"
