[package]
name = "cranko"
version = "0.0.0-dev.0"
authors = ["Peter Williams <peter@newton.cx>"]
edition = "2018"

[dependencies]
anyhow = "^1"
cargo_metadata = "^0.10"
git2 = "^0.13"
petgraph = "^0.5"
semver = "^0.9"
structopt = "^0.3"
thiserror = "1.0"
toml_edit = "^0.2"
