# Main pipeline spec for CI/CD on Azure Pipelines, strongly
# derived from Cargo's.

trigger:
  branches:
    include:
    - master
    - rc

stages:
- stage: BuildAndTest
  jobs:

  # Main Linux build(s) that create release artifacts
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: azure-test-all.yml
        parameters:
          primaryRcBuild: ${{ eq(variables['Build.SourceBranchName'], 'rc') }}
    variables:
      TOOLCHAIN: stable
      OTHER_TARGET: i686-unknown-linux-gnu

  # As far as I can tell, there is no way to matrix over a template *parameter*?
  # So we need a separate group for the "canary" jobs that test build success but
  # shouldn't create release artifacts.
  - job: Linux_canary
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: azure-test-all.yml
        parameters:
          canaryBuild: true
    strategy:
      matrix:
        beta:
          TOOLCHAIN: beta
        nightly:
          TOOLCHAIN: nightly
    variables:
      OTHER_TARGET: i686-unknown-linux-gnu

  # Mac builds
  - job: macOS
    pool:
      vmImage: macos-10.15
    steps:
      - template: azure-test-all.yml
    variables:
      TOOLCHAIN: stable
      OTHER_TARGET: x86_64-apple-ios

  # Windows builds
  - job: Windows
    pool:
      vmImage: windows-2019
    steps:
      - template: azure-test-all.yml
    strategy:
      matrix:
        x86_64-msvc:
          TOOLCHAIN: stable-x86_64-pc-windows-msvc
          OTHER_TARGET: i686-pc-windows-msvc
        x86_64-gnu:
          TOOLCHAIN: nightly-x86_64-pc-windows-gnu
          OTHER_TARGET: i686-pc-windows-gnu

  # rustfmt check
  - job: rustfmt
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: azure-install-rust.yml
      - bash: rustup component add rustfmt
        displayName: "Install rustfmt"
      - bash: cargo fmt --all -- --check
        displayName: "Check rustfmt (cargo)"
    variables:
      TOOLCHAIN: stable


# If all of those succeed and we're not in a pull request, run the deployment
# pipeline. If we're specifically on the `rc` branch, this will finalize any
# releases.
- stage: Deploy
  condition: and(succeeded('BuildAndTest'), not(eq(variables['build.reason'], 'PullRequest')))
  jobs:
  - deployment: Deploy
    environment: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-16.04

    variables:
    - group: Deployment Credentials

    strategy:
      runOnce:
        deploy:
          steps:
            - template: azure-deployment.yml
              parameters:
                rcBuild: ${{ eq(variables['Build.SourceBranchName'], 'rc') }}
