# Cranko deployment pipline, run when all CI tests pass on the `master` or `rc
# branches. NB: make sure to properly handle both cases!

parameters:
- name: rcBuild
  type: boolean
  default: false

steps:
- bash: |
    cd $(Pipeline.Workspace)
    mkdir collection
    cp binary-*/* collection/
  displayName: Collect release artifacts

- publish: $(Pipeline.Workspace)/collection
  displayName: Publish release artifacts
  artifact: artifacts

# if we're on the `rc` branch, the release has been fully vetted and the
# internal artifacts have been gathered -- time to lock in a new `release`
# commit and invoke the full release processes.

- ${{ if eq(parameters.rcBuild, true) }}:
  - checkout: self

  - bash: |
      git switch -c release
      git pull --ff-only $(Pipeline.Workspace)/git/release.bundle
      git status
      git show
      tar xzf $(Pipeline.Workspace)/binary-x86_64-unknown-linux-gnu/cranko-*.tar.gz
      ./cranko release-workflow tag
    displayName: Prepare release commit and tags

  - bash: |
      ./cranko github install-credential-helper
      git push --tags origin release:release
    displayName: Update release branch
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)

  - bash: |
      ./cranko github create-release cranko
      ./cranko github upload-artifacts cranko $(Pipeline.Workspace)/collection/*
    displayName: Create GitHub release
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
